version: "3"

services:

  # バックエンドサーバ(rails)
  backend:
    #
    # コンテナ名
    container_name: backend
    # build
    build:
      context: .
      dockerfile: ./Dockerfile
    # コンテナの中に入る
    tty: true
    # ボリューム
    volumes:
      - ".:/backend"
    # WORKDIR
    working_dir: /backend
    # 環境変数
    environment:
      TZ: "Asia/Tokyo"
      RAILS_ENV: "development"
    env_file:
      - .env.dev
    # ポート開放
    ports:
      - 3000:3000
    command: /bin/bash /docker-entrypoint.sh
